#!/usr/bin/env python3
"""Generate clearly-labelled SYNTHETIC onion-like chirp-response demo audio.

Purpose
-------
Create a tiny, license-free audio corpus so that the DSP pipeline, quality
gates, feature exporter, training script smoke-test, and demo script can be
exercised end-to-end without any external data.

What this is NOT
----------------
These are oscillator-synthesized signals inspired by published resonance
behaviour of produce (firm produce rings at higher frequencies with lower
damping; soft/defective produce rings lower with higher damping). They are
NOT recordings of onions, contain no real room acoustics or phone
transducer characteristics, and prove nothing about onion internal defects.
Every file name contains 'synthetic', and the dataset_type is 'synthetic'.

Two balanced classes are generated (8 files each):
- firmlike:  f_res 1500-2200 Hz, damping 12-25 s^-1
- defectlike: f_res 400-1000 Hz, damping 35-70 s^-1 (single or dual peak)

Usage: python tools/generate_synthetic_acoustic_demo.py [--dest DIR]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from scipy.io import wavfile

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DEST = PROJECT_ROOT / "dataset-acoustic" / "synthetic" / "demo_chirp_responses"

SAMPLE_RATE = 44100
DURATION = 1.6
SEED = 42


def make_signal(f_res: float, damping: float, dual_peak: bool, rng: np.random.Generator) -> np.ndarray:
    total = int(SAMPLE_RATE * DURATION)
    t = np.linspace(0, DURATION, total, endpoint=False)

    ambient = rng.normal(0, 0.006, total)

    chirp_dur = 1.0
    chirp_samples = int(SAMPLE_RATE * chirp_dur)
    t_chirp = t[:chirp_samples]
    f0, f1 = 100.0, 8000.0
    phase = 2 * np.pi * f0 * ((f1 / f0) ** (t_chirp / chirp_dur) - 1) / np.log(f1 / f0)
    chirp = 0.30 * np.sin(phase)
    taper = np.hanning(int(SAMPLE_RATE * 0.05) * 2)
    chirp[: len(taper) // 2] *= taper[: len(taper) // 2]
    chirp[-len(taper) // 2:] *= taper[len(taper) // 2:]

    start = int(SAMPLE_RATE * 0.3)
    t_imp = t[start:] - t[start]
    env = np.exp(-damping * t_imp)
    if dual_peak:
        ring = 0.7 * np.sin(2 * np.pi * f_res * t_imp) + 0.5 * np.sin(2 * np.pi * 2350.0 * t_imp)
    else:
        ring = np.sin(2 * np.pi * f_res * t_imp)

    signal = ambient.copy()
    signal[:chirp_samples] += chirp * 0.35
    signal[start:] += ring * env * 0.55
    peak = np.max(np.abs(signal))
    if peak > 0:
        signal = signal / peak * 0.9
    return signal


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    args = ap.parse_args()

    rng = np.random.default_rng(SEED)
    args.dest.mkdir(parents=True, exist_ok=True)

    records = []
    idx = 1
    classes = {
        "firmlike": lambda i: (float(rng.uniform(1500, 2200)), float(rng.uniform(12, 25)), False),
        "defectlike": lambda i: (float(rng.uniform(400, 1000)), float(rng.uniform(35, 70)), bool(i % 2 == 0)),
    }
    for cls in ("firmlike", "defectlike"):
        for i in range(8):
            f_res, damping, dual = classes[cls](i)
            signal = make_signal(f_res, damping, dual, rng)
            name = f"synthetic_{cls}_{idx:03d}.wav"
            path = args.dest / name
            pcm = (signal * 32767.0).astype(np.int16)
            wavfile.write(str(path), SAMPLE_RATE, pcm)
            records.append({
                "file": name,
                "class": cls,
                "synthetic_f_res_hz": round(f_res, 1),
                "synthetic_damping": round(damping, 2),
                "dual_peak": dual,
            })
            idx += 1

    label = {
        "dataset_type": "synthetic",
        "warning": (
            "SYNTHETIC DATA - generated by tools/generate_synthetic_acoustic_demo.py "
            "with seed 42. NOT recorded from onions. Contains no real transducer or "
            "room acoustics. Must never be used as onion ground truth or cited as "
            "evidence of onion internal-defect detection."
        ),
        "files": records,
    }
    with open(args.dest / "SYNTHETIC_LABEL.json", "w", encoding="utf-8") as f:
        json.dump(label, f, indent=2)
    print(f"Wrote {len(records)} synthetic WAVs to {args.dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
